# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: i@phyzait.moe
author_name: hilaolu
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyter_autorun
project_short_description: A JupyterLab extension.
python_name: jupyter_autorun
repository: https://github.com/hilaolu/jupyter_autorun
test: false

